/**
 * Maps Stratelegy /api/pbx/* proxy routes to SkySwitch Telco API paths (apiDocumentation.md).
 * Portal scope only — not every SkySwitch endpoint (151 total) is exposed to the browser.
 */

export const SKYSWITCH_API_REGISTRY = [
  {
    portal: 'GET /api/pbx/status',
    skyswitch: 'GET /accounts/{id}/pbx/domains',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/domains',
    skyswitch: 'GET /accounts/{id}/pbx/domains',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/resellers',
    skyswitch: 'GET /accounts/{id}/pbx/resellers',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/dashboard',
    skyswitch: 'multiple (domains, subscribers, e911, trunks)',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/subscribers',
    skyswitch: 'GET /accounts/{id}/pbx/subscribers',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/extensions',
    skyswitch: 'GET /accounts/{id}/pbx/subscribers?filter=subscriber',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/phone-numbers',
    skyswitch: 'GET /accounts/{id}/pbx/phone-numbers | /phone-numbers',
    scope: 'pbx|phone_number',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/ui-config',
    skyswitch: 'GET /accounts/{id}/pbx/ui-config',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/route-by-ani',
    skyswitch: 'GET /accounts/{id}/pbx/route-by-ani',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'PUT /api/pbx/route-by-ani',
    skyswitch: 'PUT /accounts/{id}/pbx/route-by-ani',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'DELETE /api/pbx/route-by-ani',
    skyswitch: 'DELETE /accounts/{id}/pbx/route-by-ani',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'POST /api/pbx/make-call',
    skyswitch: 'POST /accounts/{id}/pbx/make-call',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/routes/:phone',
    skyswitch: 'GET /accounts/{id}/phone-numbers/{phone}/route',
    scope: 'routing',
    implemented: true,
  },
  {
    portal: 'PUT /api/pbx/routes/:phone',
    skyswitch: 'PUT /accounts/{id}/phone-numbers/{phone}/route',
    scope: 'routing',
    implemented: true,
  },
  {
    portal: 'DELETE /api/pbx/routes/:phone',
    skyswitch: 'DELETE /accounts/{id}/phone-numbers/{phone}/route',
    scope: 'routing',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/e911',
    skyswitch: 'GET /accounts/{id}/e911/endpoints',
    scope: 'e911',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/e911/:phone',
    skyswitch: 'GET /accounts/{id}/phone-numbers/{phone}/e911',
    scope: 'e911',
    implemented: true,
  },
  {
    portal: 'PUT /api/pbx/e911/:phone',
    skyswitch: 'PUT /accounts/{id}/phone-numbers/{phone}/e911',
    scope: 'e911',
    implemented: true,
  },
  {
    portal: 'DELETE /api/pbx/e911/:phone',
    skyswitch: 'DELETE /accounts/{id}/phone-numbers/{phone}/e911',
    scope: 'e911',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/e911/validate/address',
    skyswitch: 'GET /accounts/{id}/e911/address',
    scope: 'e911',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/e911/countries',
    skyswitch: 'GET /accounts/{id}/e911/countries',
    scope: 'e911',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/e911/states',
    skyswitch: 'GET /accounts/{id}/e911/states',
    scope: 'e911',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/trunk-groups',
    skyswitch: 'GET /accounts/{id}/trunk-groups',
    scope: 'routing',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/auto-attendants',
    skyswitch: 'GET /accounts/{id}/auto-attendants',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/call-queues',
    skyswitch: 'GET /accounts/{id}/call-queues',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/messaging-users',
    skyswitch: 'GET /accounts/{id}/messaging/users',
    scope: 'messaging',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/messaging/aliases/pbxuser',
    skyswitch: 'GET /accounts/{id}/messaging/aliases/pbxuser',
    scope: 'messaging',
    implemented: true,
  },
  {
    portal: 'PUT /api/pbx/messaging/hubusers',
    skyswitch: 'PUT /accounts/{id}/messaging/hubusers',
    scope: 'messaging',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/reports',
    skyswitch: 'GET /accounts/{id}/reports',
    scope: 'report',
    implemented: true,
  },
  {
    portal: 'POST /api/pbx/reports',
    skyswitch: 'POST /accounts/{id}/reports',
    scope: 'report',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/reports/types',
    skyswitch: 'GET /accounts/{id}/reports/types',
    scope: 'report',
    implemented: true,
  },
  {
    portal: 'DELETE /api/pbx/reports/:id',
    skyswitch: 'DELETE /accounts/{id}/reports/{id}',
    scope: 'report',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/reports/files/:id/download',
    skyswitch: 'GET /v2/files/{file_id}',
    scope: 'report',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/audit-logs',
    skyswitch: 'GET /accounts/{id}/audit-logs',
    scope: 'log',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/offline-endpoints',
    skyswitch: 'GET /accounts/{id}/fax-atas + messaging/users',
    scope: 'pbx|messaging',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/fax-atas',
    skyswitch: 'GET /accounts/{id}/fax-atas',
    scope: 'routing',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/fax-atas/:mac/status',
    skyswitch: 'GET /accounts/{id}/fax-atas/{mac}/status',
    scope: 'routing',
    implemented: true,
  },
  {
    portal: 'POST /api/pbx/fax-atas/:mac/reboot',
    skyswitch: 'POST /accounts/{id}/fax-atas/{mac}/reboot',
    scope: 'routing',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/uc/config',
    skyswitch: 'GET /accounts/{id}/uc/config',
    scope: 'uc_config',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/uc/settings',
    skyswitch: 'GET /uc/settings',
    scope: 'uc_config',
    implemented: true,
  },
  {
    portal: 'POST /api/pbx/uc/config-rules',
    skyswitch: 'POST /accounts/{id}/uc/config-rules',
    scope: 'uc_config',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/uc/config-rules/:id',
    skyswitch: 'GET /accounts/{id}/uc/config-rules/{id}',
    scope: 'uc_config',
    implemented: true,
  },
  {
    portal: 'DELETE /api/pbx/uc/config-rules/:id',
    skyswitch: 'DELETE /accounts/{id}/uc/config-rules/{id}',
    scope: 'uc_config',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/entitlements',
    skyswitch: 'GET /accounts/{id}/entitlements',
    scope: 'entitlement',
    implemented: true,
  },
  {
    portal: 'PUT /api/pbx/entitlements',
    skyswitch: 'PUT /accounts/{id}/entitlements',
    scope: 'entitlement',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/entitlements/offerings',
    skyswitch: 'GET /accounts/{id}/entitlements/offerings',
    scope: 'entitlement',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/entitlements/offeroptions',
    skyswitch: 'GET /accounts/{id}/entitlements/offeroptions',
    scope: 'entitlement',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/entitlements/offervalue',
    skyswitch: 'GET /accounts/{id}/entitlements/offervalue',
    scope: 'entitlement',
    implemented: true,
  },
  {
    portal: 'DELETE /api/pbx/entitlements/:id',
    skyswitch: 'DELETE /accounts/{id}/entitlements/{id}',
    scope: 'entitlement',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/cnam-outbound/:phone',
    skyswitch: 'GET /accounts/{id}/phone-numbers/{phone}/cnam-outbound/enum',
    scope: 'phone_number',
    implemented: true,
  },
  {
    portal: 'PUT /api/pbx/cnam-outbound/:phone',
    skyswitch: 'PUT /accounts/{id}/phone-numbers/{phone}/cnam-outbound/neustar',
    scope: 'phone_number',
    implemented: true,
  },
  {
    portal: 'DELETE /api/pbx/cnam-outbound/:phone',
    skyswitch: 'DELETE /accounts/{id}/phone-numbers/{phone}/cnam-outbound/neustar',
    scope: 'phone_number',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/audit-logs/resource-actions',
    skyswitch: 'GET /accounts/{id}/audit-logs/resource-actions',
    scope: 'log',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/journals',
    skyswitch: 'GET /accounts/{id}/journals',
    scope: 'log',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/journals/module-type-actions',
    skyswitch: 'GET /accounts/{id}/journals/module-type-actions',
    scope: 'log',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/troubleshooting/vulnerability',
    skyswitch: 'PBX subscriber read + domain read (dial_policy, vm_pin, call_limit)',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'PATCH /api/pbx/troubleshooting/vulnerability/call-limit',
    skyswitch: 'PBX domain update (call_limit)',
    scope: 'pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/endpoint-control/overview',
    skyswitch: 'GET /accounts/{id}/pbx/subscribers + messaging + sip-alg',
    scope: 'pbx|messaging',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/e911/review-overview',
    skyswitch: 'GET e911/endpoints + pbx/subscribers',
    scope: 'e911|pbx',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/offline-endpoints/overview',
    skyswitch: 'GET fax-atas + pbx/subscribers',
    scope: 'pbx|routing',
    implemented: true,
  },
  {
    portal: 'GET /api/pbx/mos-scores',
    skyswitch: 'GET /accounts/{id}/journals (filtered)',
    scope: 'log',
    implemented: true,
  },
];

/** SkySwitch areas documented but intentionally not proxied (admin/back-office tooling). */
export const SKYSWITCH_OUT_OF_SCOPE = [
  'tendlc (21 endpoints)',
  'tfa2p (9 endpoints)',
  'port-in / lnp',
  'catalog / inventory purchase flows',
  'users / sub-accounts CRUD',
  'branding',
  'billing',
];

/** Reports: public docs list types/status/cancel/download; POST queue works at runtime. */
export const REPORTS_API_NOTE =
  'POST /accounts/{id}/reports queues async exports (undocumented in public reference; verified at runtime).';
